Kripto 1
divisi-security-poros/WU-PicoCTF-2019 pull request #20
Opened 2020-08-22 16:20 UTC by vnwrywn

Tambah 5 Soal Total

2020-08-25 06:53 UTC, joulephicar requested changes
tolong perbaiki

2020-08-25 06:53 UTC, joulephicar commented on Kriptografi/WriteUP [vnwrywn].md
> +| [waves over lambda](#5-waves-over-lambda-300)|
fokus dong, aku buat guide dibaca bagian soal mu apa aja, seingetku yang kutulis disini itu
```suggestion
| [The Numbers](#1-the-numbers-50)     |
| [caesar](#2-caesar-100)               |
| [Flags]()                         |
| [la cifra de]()                   |
| [rsa-pop-quiz]()                  |
| [waves over lambda]()             |
```

jangan ditambah2in soalnya sama yang di cabang kripto-2. Selesain dulu itu.

2020-08-25 06:53 UTC, joulephicar commented on Kriptografi/WriteUP [vnwrywn].md
> +...
sesuaikan

2020-08-25 06:53 UTC, joulephicar commented on Kriptografi/WriteUP [Seseorang01].md
> +##
Ini template awal bagian mu, tinggal diterusin aja ya.

2020-08-25 10:20 UTC, vnwrywn reviewed
Sudah diperbaiki sesuai guide

2020-08-25 10:24 UTC, vnwrywn commented
Sudah diperbaiki sesuai guide

2020-08-27 13:19 UTC, joulephicar approved these changes
acc

2020-08-27 13:22 UTC, merged